# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash
set -e

COLOR=$1   # blue or green
OTHER_COLOR=green
if [ "$COLOR" = "green" ]; then
  OTHER_COLOR=blue
fi

docker pull myrepo/myapp:latest

# Run new container
docker run -d --name app_${COLOR} -p 5001:5000 myrepo/myapp:latest

# Switch the traffic (e.g., via nginx or updating ELB target group)
./switch_traffic.sh $COLOR

# Stop the old container
docker stop app_${OTHER_COLOR} || true
docker rm app_${OTHER_COLOR} || true
