// Code Generated by Sidekick is for learning and experimentation purposes only.
pipeline {
    agent any
    environment {
        APP_NAME = 'myapp'
        DOCKER_REPO = 'myrepo/myapp'
        SSH_USER = 'ec2-user'
        HOST = 'ec2-public-dns'
        COLOR = '' // will be dynamically set
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("$DOCKER_REPO:latest", ".")
                }
            }
        }
        stage('Push to Registry') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-credentials') {
                        docker.image("$DOCKER_REPO:latest").push()
                    }
                }
            }
        }
        stage('Choose Color') {
            steps {
                script {
                    // SSH to EC2 and detect which app is running
                    def current = sh(script: "ssh $SSH_USER@$HOST 'docker ps --format \"{{. Names}}\" | grep app_blue || echo green'", returnStdout: true).trim()
                    env.COLOR = (current == 'app_blue') ? 'green' : 'blue'
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    sh "scp deploy.sh switch_traffic.sh $SSH_USER@$HOST:/home/$SSH_USER/"
                    sh "ssh $SSH_USER@$HOST 'chmod +x deploy.sh switch_traffic.sh && ./deploy.sh $COLOR'"
                }
            }
        }
    }
}
