# Code Generated by Sidekick is for learning and experimentation purposes only.
#!/bin/bash
COLOR=$1

if [ "$COLOR" = "blue" ]; then
  TARGET_PORT=5001
else
  TARGET_PORT=5002
fi

cat > /etc/nginx/conf.d/app.conf <<EOL
server {
    listen 80;
    location / {
        proxy_pass http://localhost:$TARGET_PORT;
    }
}
EOL

nginx -s reload
